server:
  port: 8888
  
spring:
  application:
    name: 'api-gateway'
    
# Registering application in Eureka Server  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

# Configuring exposure of routes find in eureka  
management:
 endpoints:
  web:
   exposure:
    include:
    - "routes"
 
# Configuring headers to be forwarded to applications  
zuul:
 sensitive-headers:
 - Cookie, Authorization
 
s3-service:
  ribbon:
    ReadTimeout: 3000
    
product-service:
  ribbon:
    ReadTimeout: 3000