spring:
  application:
    name: 'product-service'
  data:
    mongodb:
      database: product-service-db
      port: 27017
      host: localhost

server:
  port: 8084
    
# Registering application in Eureka Server  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8081/eureka

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8085/v1/auth
      
management:
  endpoints:
    web:
      exposure:
        include:
        - hystrix.stream, info, health
      base-path: /
      
# enable the share of configuration between spring and hystrix threads   
hystrix:
 shareSecurityContext: true
      
bucket: spring-demo-products